export const PREQUOTE_ERROR_CODES = {
  invalidRequest: "PREQUOTE_INVALID_REQUEST",
  unauthorized: "AUTH_UNAUTHORIZED",
  inactiveUser: "AUTH_USER_INACTIVE",
  projectNotFound: "PREQUOTE_PROJECT_NOT_FOUND",
  projectInactive: "PREQUOTE_PROJECT_INACTIVE",
  clientNotFound: "PREQUOTE_CLIENT_NOT_FOUND",
  clientInactive: "PREQUOTE_CLIENT_INACTIVE",
  queryError: "PREQUOTE_QUERY_ERROR",
  persistenceError: "PREQUOTE_PERSISTENCE_ERROR",
  listInvalidRequest: "PREQUOTE_LIST_INVALID_REQUEST",
  listQueryError: "PREQUOTE_LIST_QUERY_ERROR",
  documentsInvalidRequest: "PREQUOTE_DOCUMENTS_INVALID_REQUEST",
  documentsQueryError: "PREQUOTE_DOCUMENTS_QUERY_ERROR",
  notFound: "PREQUOTE_NOT_FOUND",
  documentInvalidRequest: "DOCUMENT_INVALID_REQUEST",
  documentUnsupportedFileType: "DOCUMENT_UNSUPPORTED_FILE_TYPE",
  documentEmptyFile: "DOCUMENT_EMPTY_FILE",
  documentFileTooLarge: "DOCUMENT_FILE_TOO_LARGE",
  documentPreQuoteNotFound: "DOCUMENT_PREQUOTE_NOT_FOUND",
  documentProjectInactive: "DOCUMENT_PROJECT_INACTIVE",
  documentClientInactive: "DOCUMENT_CLIENT_INACTIVE",
  documentStorageError: "DOCUMENT_STORAGE_ERROR",
  documentPersistenceError: "DOCUMENT_PERSISTENCE_ERROR",
  processingInvalidRequest: "DOCUMENT_PROCESSING_INVALID_REQUEST",
  processingDocumentNotFound: "PREQUOTE_DOCUMENT_NOT_FOUND",
  processingProjectInactive: "PREQUOTE_PROJECT_INACTIVE",
  processingClientInactive: "PREQUOTE_CLIENT_INACTIVE",
  processingAlreadyActive: "DOCUMENT_PROCESSING_ALREADY_ACTIVE",
  processingQueryError: "DOCUMENT_PROCESSING_QUERY_ERROR",
  processingPersistenceError: "DOCUMENT_PROCESSING_PERSISTENCE_ERROR",
  processingAttemptInvalidRequest:
    "DOCUMENT_PROCESSING_ATTEMPT_INVALID_REQUEST",
  processingAttemptNotFound: "DOCUMENT_PROCESSING_ATTEMPT_NOT_FOUND",
  processingAttemptQueryError: "DOCUMENT_PROCESSING_ATTEMPT_QUERY_ERROR",
  structuredExtractionInvalidRequest: "STRUCTURED_EXTRACTION_INVALID_REQUEST",
  structuredExtractionQueryError: "STRUCTURED_EXTRACTION_QUERY_ERROR",
  structuredExtractionNotFound: "STRUCTURED_EXTRACTION_NOT_FOUND",
} as const;
